//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="")]
    public partial class Login : object
    {
        
        private string UserField;
        
        private string PassField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Pass
        {
            get
            {
                return this.PassField;
            }
            set
            {
                this.PassField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="")]
    public partial class Order : object
    {
        
        private string ORD_ORDINEField;
        
        private string ORD_DESField;
        
        private string RIG_ARTICOLOField;
        
        private string RIG_SUB1Field;
        
        private string RIG_HOSTINFField;
        
        private string RIG_QTARField;
        
        private string ART_DESField;
        
        private string ART_UMIField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ORD_ORDINE
        {
            get
            {
                return this.ORD_ORDINEField;
            }
            set
            {
                this.ORD_ORDINEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ORD_DES
        {
            get
            {
                return this.ORD_DESField;
            }
            set
            {
                this.ORD_DESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string RIG_ARTICOLO
        {
            get
            {
                return this.RIG_ARTICOLOField;
            }
            set
            {
                this.RIG_ARTICOLOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string RIG_SUB1
        {
            get
            {
                return this.RIG_SUB1Field;
            }
            set
            {
                this.RIG_SUB1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string RIG_HOSTINF
        {
            get
            {
                return this.RIG_HOSTINFField;
            }
            set
            {
                this.RIG_HOSTINFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string RIG_QTAR
        {
            get
            {
                return this.RIG_QTARField;
            }
            set
            {
                this.RIG_QTARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string ART_DES
        {
            get
            {
                return this.ART_DESField;
            }
            set
            {
                this.ART_DESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string ART_UMI
        {
            get
            {
                return this.ART_UMIField;
            }
            set
            {
                this.ART_UMIField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="")]
    public partial class Result : object
    {
        
        private string StatusField;
        
        private string MessageField;
        
        private int OrdersField;
        
        private int RowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Orders
        {
            get
            {
                return this.OrdersField;
            }
            set
            {
                this.OrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="")]
    public partial class Item : object
    {
        
        private string ART_ARTICOLOField;
        
        private string ART_DESField;
        
        private string ART_UMIField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ART_ARTICOLO
        {
            get
            {
                return this.ART_ARTICOLOField;
            }
            set
            {
                this.ART_ARTICOLOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ART_DES
        {
            get
            {
                return this.ART_DESField;
            }
            set
            {
                this.ART_DESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ART_UMI
        {
            get
            {
                return this.ART_UMIField;
            }
            set
            {
                this.ART_UMIField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Maintenance", Namespace="")]
    public partial class Maintenance : object
    {
        
        private string ORD_ORDINEField;
        
        private string ORD_DESField;
        
        private string RIG_ARTICOLOField;
        
        private string RIG_SUB1Field;
        
        private string RIG_HOSTINFField;
        
        private string RIG_QTARField;
        
        private string RIG_REQ_NOTEField;
        
        private string RIG_PRIOField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ORD_ORDINE
        {
            get
            {
                return this.ORD_ORDINEField;
            }
            set
            {
                this.ORD_ORDINEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ORD_DES
        {
            get
            {
                return this.ORD_DESField;
            }
            set
            {
                this.ORD_DESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string RIG_ARTICOLO
        {
            get
            {
                return this.RIG_ARTICOLOField;
            }
            set
            {
                this.RIG_ARTICOLOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string RIG_SUB1
        {
            get
            {
                return this.RIG_SUB1Field;
            }
            set
            {
                this.RIG_SUB1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string RIG_HOSTINF
        {
            get
            {
                return this.RIG_HOSTINFField;
            }
            set
            {
                this.RIG_HOSTINFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string RIG_QTAR
        {
            get
            {
                return this.RIG_QTARField;
            }
            set
            {
                this.RIG_QTARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string RIG_REQ_NOTE
        {
            get
            {
                return this.RIG_REQ_NOTEField;
            }
            set
            {
                this.RIG_REQ_NOTEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string RIG_PRIO
        {
            get
            {
                return this.RIG_PRIOField;
            }
            set
            {
                this.RIG_PRIOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference2.IInterface")]
    public interface IInterface
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IInterface/postInbound", ReplyAction="urn:IInterface/postInboundResponse")]
        ServiceReference2.Result[] postInbound(ServiceReference2.Login Login, ServiceReference2.Order[] Orders);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IInterface/postInbound", ReplyAction="urn:IInterface/postInboundResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Result[]> postInboundAsync(ServiceReference2.Login Login, ServiceReference2.Order[] Orders);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IInterface/postItemMaster", ReplyAction="urn:IInterface/postItemMasterResponse")]
        ServiceReference2.Result[] postItemMaster(ServiceReference2.Login Login, ServiceReference2.Item[] Items);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IInterface/postItemMaster", ReplyAction="urn:IInterface/postItemMasterResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Result[]> postItemMasterAsync(ServiceReference2.Login Login, ServiceReference2.Item[] Items);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IInterface/postMaintenance", ReplyAction="urn:IInterface/postMaintenanceResponse")]
        ServiceReference2.Result[] postMaintenance(ServiceReference2.Login Login, ServiceReference2.Maintenance[] Orders);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IInterface/postMaintenance", ReplyAction="urn:IInterface/postMaintenanceResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Result[]> postMaintenanceAsync(ServiceReference2.Login Login, ServiceReference2.Maintenance[] Orders);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IInterfaceChannel : ServiceReference2.IInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class InterfaceClient : System.ServiceModel.ClientBase<ServiceReference2.IInterface>, ServiceReference2.IInterface
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InterfaceClient() : 
                base(InterfaceClient.GetDefaultBinding(), InterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IInterface.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(EndpointConfiguration endpointConfiguration) : 
                base(InterfaceClient.GetBindingForEndpoint(endpointConfiguration), InterfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference2.Result[] postInbound(ServiceReference2.Login Login, ServiceReference2.Order[] Orders)
        {
            return base.Channel.postInbound(Login, Orders);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Result[]> postInboundAsync(ServiceReference2.Login Login, ServiceReference2.Order[] Orders)
        {
            return base.Channel.postInboundAsync(Login, Orders);
        }
        
        public ServiceReference2.Result[] postItemMaster(ServiceReference2.Login Login, ServiceReference2.Item[] Items)
        {
            return base.Channel.postItemMaster(Login, Items);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Result[]> postItemMasterAsync(ServiceReference2.Login Login, ServiceReference2.Item[] Items)
        {
            return base.Channel.postItemMasterAsync(Login, Items);
        }
        
        public ServiceReference2.Result[] postMaintenance(ServiceReference2.Login Login, ServiceReference2.Maintenance[] Orders)
        {
            return base.Channel.postMaintenance(Login, Orders);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Result[]> postMaintenanceAsync(ServiceReference2.Login Login, ServiceReference2.Maintenance[] Orders)
        {
            return base.Channel.postMaintenanceAsync(Login, Orders);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInterface))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInterface))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.220/Modula/api/Interface.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InterfaceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IInterface);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InterfaceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IInterface);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IInterface,
        }
    }
}
