//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class Response : object
    {
        
        private string codeField;
        
        private string messageField;
        
        private string pdfField;
        
        private string uuidField;
        
        private string xmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseTimbrado", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseTimbrado : object
    {
        
        private string codeField;
        
        private string messageField;
        
        private string qrField;
        
        private string uuidField;
        
        private string xmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qr
        {
            get
            {
                return this.qrField;
            }
            set
            {
                this.qrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCancelacion", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseCancelacion : object
    {
        
        private bool EstatusField;
        
        private string acuseField;
        
        private string codeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estatus
        {
            get
            {
                return this.EstatusField;
            }
            set
            {
                this.EstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string acuse
        {
            get
            {
                return this.acuseField;
            }
            set
            {
                this.acuseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsePeticionesPendientes", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponsePeticionesPendientes : object
    {
        
        private ServiceReference1.AcusePeticionesPendientes AcuseField;
        
        private string codeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AcusePeticionesPendientes Acuse
        {
            get
            {
                return this.AcuseField;
            }
            set
            {
                this.AcuseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcusePeticionesPendientes", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class AcusePeticionesPendientes : object
    {
        
        private string codEstatusFieldField;
        
        private string[] uUIDFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codEstatusField
        {
            get
            {
                return this.codEstatusFieldField;
            }
            set
            {
                this.codEstatusFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] uUIDField
        {
            get
            {
                return this.uUIDFieldField;
            }
            set
            {
                this.uUIDFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseConsultaCfdisRelacionados", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseConsultaCfdisRelacionados : object
    {
        
        private ServiceReference1.ConsultaRelacionados AcuseField;
        
        private string codeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ConsultaRelacionados Acuse
        {
            get
            {
                return this.AcuseField;
            }
            set
            {
                this.AcuseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaRelacionados", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioCo" +
        "nsultaCFDIRelacionados")]
    public partial class ConsultaRelacionados : object
    {
        
        private string resultadoFieldField;
        
        private string uuidConsultadoFieldField;
        
        private ServiceReference1.UuidRelacionado[] uuidsRelacionadosHijosFieldField;
        
        private ServiceReference1.UuidPadre[] uuidsRelacionadosPadresFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string resultadoField
        {
            get
            {
                return this.resultadoFieldField;
            }
            set
            {
                this.resultadoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uuidConsultadoField
        {
            get
            {
                return this.uuidConsultadoFieldField;
            }
            set
            {
                this.uuidConsultadoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.UuidRelacionado[] uuidsRelacionadosHijosField
        {
            get
            {
                return this.uuidsRelacionadosHijosFieldField;
            }
            set
            {
                this.uuidsRelacionadosHijosFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.UuidPadre[] uuidsRelacionadosPadresField
        {
            get
            {
                return this.uuidsRelacionadosPadresFieldField;
            }
            set
            {
                this.uuidsRelacionadosPadresFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UuidRelacionado", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioCo" +
        "nsultaCFDIRelacionados")]
    public partial class UuidRelacionado : object
    {
        
        private string rfcEmisorFieldField;
        
        private string rfcReceptorFieldField;
        
        private string uuidFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rfcEmisorField
        {
            get
            {
                return this.rfcEmisorFieldField;
            }
            set
            {
                this.rfcEmisorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rfcReceptorField
        {
            get
            {
                return this.rfcReceptorFieldField;
            }
            set
            {
                this.rfcReceptorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uuidField
        {
            get
            {
                return this.uuidFieldField;
            }
            set
            {
                this.uuidFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UuidPadre", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioCo" +
        "nsultaCFDIRelacionados")]
    public partial class UuidPadre : object
    {
        
        private string rfcEmisorFieldField;
        
        private string rfcReceptorFieldField;
        
        private string uuidFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rfcEmisorField
        {
            get
            {
                return this.rfcEmisorFieldField;
            }
            set
            {
                this.rfcEmisorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rfcReceptorField
        {
            get
            {
                return this.rfcReceptorFieldField;
            }
            set
            {
                this.rfcReceptorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uuidField
        {
            get
            {
                return this.uuidFieldField;
            }
            set
            {
                this.uuidFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseConsultaEstatus", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseConsultaEstatus : object
    {
        
        private ServiceReference1.Acuse AcuseField;
        
        private string codeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Acuse Acuse
        {
            get
            {
                return this.AcuseField;
            }
            set
            {
                this.AcuseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Acuse", Namespace="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio")]
    public partial class Acuse : object
    {
        
        private string CodigoEstatusField;
        
        private string EsCancelableField;
        
        private string EstadoField;
        
        private string EstatusCancelacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEstatus
        {
            get
            {
                return this.CodigoEstatusField;
            }
            set
            {
                this.CodigoEstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsCancelable
        {
            get
            {
                return this.EsCancelableField;
            }
            set
            {
                this.EsCancelableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstatusCancelacion
        {
            get
            {
                return this.EstatusCancelacionField;
            }
            set
            {
                this.EstatusCancelacionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAccionPeticionCancelacion", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public enum TipoAccionPeticionCancelacion : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aceptacion = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rechazo = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseAceptacionRechazo", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseAceptacionRechazo : object
    {
        
        private ServiceReference1.AcuseAceptacionRechazo AcuseField;
        
        private string codeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AcuseAceptacionRechazo Acuse
        {
            get
            {
                return this.AcuseField;
            }
            set
            {
                this.AcuseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcuseAceptacionRechazo", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class AcuseAceptacionRechazo : object
    {
        
        private string codEstatusFieldField;
        
        private System.DateTime fechaFieldField;
        
        private ServiceReference1.AcuseAceptacionRechazoFolios[] foliosFieldField;
        
        private string rfcPacFieldField;
        
        private string rfcReceptorFieldField;
        
        private ServiceReference1.SignatureType signatureFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codEstatusField
        {
            get
            {
                return this.codEstatusFieldField;
            }
            set
            {
                this.codEstatusFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime fechaField
        {
            get
            {
                return this.fechaFieldField;
            }
            set
            {
                this.fechaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.AcuseAceptacionRechazoFolios[] foliosField
        {
            get
            {
                return this.foliosFieldField;
            }
            set
            {
                this.foliosFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rfcPacField
        {
            get
            {
                return this.rfcPacFieldField;
            }
            set
            {
                this.rfcPacFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rfcReceptorField
        {
            get
            {
                return this.rfcReceptorFieldField;
            }
            set
            {
                this.rfcReceptorFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.SignatureType signatureField
        {
            get
            {
                return this.signatureFieldField;
            }
            set
            {
                this.signatureFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class SignatureType : object
    {
        
        private string idFieldField;
        
        private ServiceReference1.KeyInfoType keyInfoFieldField;
        
        private ServiceReference1.ObjectType[] objectFieldField;
        
        private byte[] signatureValueFieldField;
        
        private ServiceReference1.SignedInfoType signedInfoFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idField
        {
            get
            {
                return this.idFieldField;
            }
            set
            {
                this.idFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.KeyInfoType keyInfoField
        {
            get
            {
                return this.keyInfoFieldField;
            }
            set
            {
                this.keyInfoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.ObjectType[] objectField
        {
            get
            {
                return this.objectFieldField;
            }
            set
            {
                this.objectFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] signatureValueField
        {
            get
            {
                return this.signatureValueFieldField;
            }
            set
            {
                this.signatureValueFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.SignedInfoType signedInfoField
        {
            get
            {
                return this.signedInfoFieldField;
            }
            set
            {
                this.signedInfoFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcuseAceptacionRechazoFolios", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class AcuseAceptacionRechazoFolios : object
    {
        
        private string estatusUUIDFieldField;
        
        private string respuestaFieldField;
        
        private string uUIDFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string estatusUUIDField
        {
            get
            {
                return this.estatusUUIDFieldField;
            }
            set
            {
                this.estatusUUIDFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string respuestaField
        {
            get
            {
                return this.respuestaFieldField;
            }
            set
            {
                this.respuestaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uUIDField
        {
            get
            {
                return this.uUIDFieldField;
            }
            set
            {
                this.uUIDFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyInfoType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class KeyInfoType : object
    {
        
        private string idFieldField;
        
        private string keyNameFieldField;
        
        private ServiceReference1.KeyValueType keyValueFieldField;
        
        private string[] textFieldField;
        
        private ServiceReference1.X509DataType x509DataFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idField
        {
            get
            {
                return this.idFieldField;
            }
            set
            {
                this.idFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string keyNameField
        {
            get
            {
                return this.keyNameFieldField;
            }
            set
            {
                this.keyNameFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.KeyValueType keyValueField
        {
            get
            {
                return this.keyValueFieldField;
            }
            set
            {
                this.keyValueFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.X509DataType x509DataField
        {
            get
            {
                return this.x509DataFieldField;
            }
            set
            {
                this.x509DataFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedInfoType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class SignedInfoType : object
    {
        
        private ServiceReference1.CanonicalizationMethodType canonicalizationMethodFieldField;
        
        private string idFieldField;
        
        private ServiceReference1.ReferenceType referenceFieldField;
        
        private ServiceReference1.SignatureMethodType signatureMethodFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.CanonicalizationMethodType canonicalizationMethodField
        {
            get
            {
                return this.canonicalizationMethodFieldField;
            }
            set
            {
                this.canonicalizationMethodFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idField
        {
            get
            {
                return this.idFieldField;
            }
            set
            {
                this.idFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.ReferenceType referenceField
        {
            get
            {
                return this.referenceFieldField;
            }
            set
            {
                this.referenceFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.SignatureMethodType signatureMethodField
        {
            get
            {
                return this.signatureMethodFieldField;
            }
            set
            {
                this.signatureMethodFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class ObjectType : object
    {
        
        private System.Xml.XmlNode[] anyFieldField;
        
        private string encodingFieldField;
        
        private string idFieldField;
        
        private string mimeTypeFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Xml.XmlNode[] anyField
        {
            get
            {
                return this.anyFieldField;
            }
            set
            {
                this.anyFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string encodingField
        {
            get
            {
                return this.encodingFieldField;
            }
            set
            {
                this.encodingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idField
        {
            get
            {
                return this.idFieldField;
            }
            set
            {
                this.idFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mimeTypeField
        {
            get
            {
                return this.mimeTypeFieldField;
            }
            set
            {
                this.mimeTypeFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValueType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class KeyValueType : object
    {
        
        private ServiceReference1.RSAKeyValueType rSAKeyValueFieldField;
        
        private string[] textFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.RSAKeyValueType rSAKeyValueField
        {
            get
            {
                return this.rSAKeyValueFieldField;
            }
            set
            {
                this.rSAKeyValueFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="X509DataType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class X509DataType : object
    {
        
        private byte[] x509CertificateFieldField;
        
        private ServiceReference1.X509IssuerSerialType x509IssuerSerialFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] x509CertificateField
        {
            get
            {
                return this.x509CertificateFieldField;
            }
            set
            {
                this.x509CertificateFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.X509IssuerSerialType x509IssuerSerialField
        {
            get
            {
                return this.x509IssuerSerialFieldField;
            }
            set
            {
                this.x509IssuerSerialFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RSAKeyValueType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class RSAKeyValueType : object
    {
        
        private byte[] exponentFieldField;
        
        private byte[] modulusFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] exponentField
        {
            get
            {
                return this.exponentFieldField;
            }
            set
            {
                this.exponentFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] modulusField
        {
            get
            {
                return this.modulusFieldField;
            }
            set
            {
                this.modulusFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="X509IssuerSerialType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class X509IssuerSerialType : object
    {
        
        private string x509IssuerNameFieldField;
        
        private string x509SerialNumberFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string x509IssuerNameField
        {
            get
            {
                return this.x509IssuerNameFieldField;
            }
            set
            {
                this.x509IssuerNameFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string x509SerialNumberField
        {
            get
            {
                return this.x509SerialNumberFieldField;
            }
            set
            {
                this.x509SerialNumberFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanonicalizationMethodType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class CanonicalizationMethodType : object
    {
        
        private string algorithmFieldField;
        
        private System.Xml.XmlNode[] anyFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string algorithmField
        {
            get
            {
                return this.algorithmFieldField;
            }
            set
            {
                this.algorithmFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Xml.XmlNode[] anyField
        {
            get
            {
                return this.anyFieldField;
            }
            set
            {
                this.anyFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class ReferenceType : object
    {
        
        private ServiceReference1.DigestMethodType digestMethodFieldField;
        
        private byte[] digestValueFieldField;
        
        private string idFieldField;
        
        private ServiceReference1.TransformType[] transformsFieldField;
        
        private string typeFieldField;
        
        private string uRIFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.DigestMethodType digestMethodField
        {
            get
            {
                return this.digestMethodFieldField;
            }
            set
            {
                this.digestMethodFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] digestValueField
        {
            get
            {
                return this.digestValueFieldField;
            }
            set
            {
                this.digestValueFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idField
        {
            get
            {
                return this.idFieldField;
            }
            set
            {
                this.idFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.TransformType[] transformsField
        {
            get
            {
                return this.transformsFieldField;
            }
            set
            {
                this.transformsFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string typeField
        {
            get
            {
                return this.typeFieldField;
            }
            set
            {
                this.typeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string uRIField
        {
            get
            {
                return this.uRIFieldField;
            }
            set
            {
                this.uRIFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureMethodType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class SignatureMethodType : object
    {
        
        private string algorithmFieldField;
        
        private System.Xml.XmlNode[] anyFieldField;
        
        private string hMACOutputLengthFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string algorithmField
        {
            get
            {
                return this.algorithmFieldField;
            }
            set
            {
                this.algorithmFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Xml.XmlNode[] anyField
        {
            get
            {
                return this.anyFieldField;
            }
            set
            {
                this.anyFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string hMACOutputLengthField
        {
            get
            {
                return this.hMACOutputLengthFieldField;
            }
            set
            {
                this.hMACOutputLengthFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigestMethodType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class DigestMethodType : object
    {
        
        private string algorithmFieldField;
        
        private System.Xml.XmlNode[] anyFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string algorithmField
        {
            get
            {
                return this.algorithmFieldField;
            }
            set
            {
                this.algorithmFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Xml.XmlNode[] anyField
        {
            get
            {
                return this.anyFieldField;
            }
            set
            {
                this.anyFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransformType", Namespace="http://schemas.datacontract.org/2004/07/SAT.CFDI.Cliente.Procesamiento.ServicioAc" +
        "eptacionRechazoCFDI")]
    public partial class TransformType : object
    {
        
        private string algorithmFieldField;
        
        private string[] textFieldField;
        
        private string xPathFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string algorithmField
        {
            get
            {
                return this.algorithmFieldField;
            }
            set
            {
                this.algorithmFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] textField
        {
            get
            {
                return this.textFieldField;
            }
            set
            {
                this.textFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string xPathField
        {
            get
            {
                return this.xPathFieldField;
            }
            set
            {
                this.xPathFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCertificado", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseCertificado : object
    {
        
        private System.Nullable<System.DateTime> ExpiraField;
        
        private string MensajeField;
        
        private string NoCertificadoField;
        
        private string RFCField;
        
        private System.Nullable<System.DateTime> VigenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Expira
        {
            get
            {
                return this.ExpiraField;
            }
            set
            {
                this.ExpiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoCertificado
        {
            get
            {
                return this.NoCertificadoField;
            }
            set
            {
                this.NoCertificadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Vigencia
        {
            get
            {
                return this.VigenciaField;
            }
            set
            {
                this.VigenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseConsultaEmpresas", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseConsultaEmpresas : object
    {
        
        private string ObservacionesField;
        
        private string rfcField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfc
        {
            get
            {
                return this.rfcField;
            }
            set
            {
                this.rfcField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseConsultaDetallada", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseConsultaDetallada : object
    {
        
        private string ObservacionesField;
        
        private int TimbresCanceladosField;
        
        private int TimbresDisponiblesField;
        
        private int TimbresVigentesField;
        
        private string rfcField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresCancelados
        {
            get
            {
                return this.TimbresCanceladosField;
            }
            set
            {
                this.TimbresCanceladosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresDisponibles
        {
            get
            {
                return this.TimbresDisponiblesField;
            }
            set
            {
                this.TimbresDisponiblesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimbresVigentes
        {
            get
            {
                return this.TimbresVigentesField;
            }
            set
            {
                this.TimbresVigentesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfc
        {
            get
            {
                return this.rfcField;
            }
            set
            {
                this.rfcField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseTimbradoBase64", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi")]
    public partial class ResponseTimbradoBase64 : object
    {
        
        private string codeField;
        
        private string messageField;
        
        private string uuidField;
        
        private string xmlBase64Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xmlBase64
        {
            get
            {
                return this.xmlBase64Field;
            }
            set
            {
                this.xmlBase64Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsePDF", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi.BLL.Models" +
        "")]
    public partial class ResponsePDF : object
    {
        
        private ServiceReference1.DatosPDF ConsultadoField;
        
        private ServiceReference1.DatosPDF EnviadoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DatosPDF Consultado
        {
            get
            {
                return this.ConsultadoField;
            }
            set
            {
                this.ConsultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DatosPDF Enviado
        {
            get
            {
                return this.EnviadoField;
            }
            set
            {
                this.EnviadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosPDF", Namespace="http://schemas.datacontract.org/2004/07/DigitalInvoice.SegurosElPotosi.BLL.Models" +
        "")]
    public partial class DatosPDF : object
    {
        
        private string FechaField;
        
        private string FolioField;
        
        private string RFCField;
        
        private string SentidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio
        {
            get
            {
                return this.FolioField;
            }
            set
            {
                this.FolioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sentido
        {
            get
            {
                return this.SentidoField;
            }
            set
            {
                this.SentidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITimbradoService")]
    public interface ITimbradoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Timbrar", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarResponse")]
        ServiceReference1.Response Timbrar(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Timbrar", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarTest", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarTestResponse")]
        ServiceReference1.Response TimbrarTest(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarTest", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarTestResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarTestAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Timbrar40", ReplyAction="http://tempuri.org/ITimbradoService/Timbrar40Response")]
        ServiceReference1.Response Timbrar40(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Timbrar40", ReplyAction="http://tempuri.org/ITimbradoService/Timbrar40Response")]
        System.Threading.Tasks.Task<ServiceReference1.Response> Timbrar40Async(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Timbrar40Test", ReplyAction="http://tempuri.org/ITimbradoService/Timbrar40TestResponse")]
        ServiceReference1.Response Timbrar40Test(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Timbrar40Test", ReplyAction="http://tempuri.org/ITimbradoService/Timbrar40TestResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> Timbrar40TestAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSellarBase64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSellarBase64Response")]
        ServiceReference1.Response TimbrarSellarBase64(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSellarBase64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSellarBase64Response")]
        System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSellarBase64Async(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSellarBase64Test", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSellarBase64TestResponse")]
        ServiceReference1.Response TimbrarSellarBase64Test(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSellarBase64Test", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSellarBase64TestResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSellarBase64TestAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarBase64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarBase64Response")]
        ServiceReference1.ResponseTimbrado TimbrarBase64(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarBase64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarBase64Response")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> TimbrarBase64Async(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarTestBase64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarTestBase64Response")]
        ServiceReference1.ResponseTimbrado TimbrarTestBase64(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarTestBase64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarTestBase64Response")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> TimbrarTestBase64Async(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/GetCfdi", ReplyAction="http://tempuri.org/ITimbradoService/GetCfdiResponse")]
        ServiceReference1.ResponseTimbrado GetCfdi(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/GetCfdi", ReplyAction="http://tempuri.org/ITimbradoService/GetCfdiResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> GetCfdiAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/GetCfdiTest", ReplyAction="http://tempuri.org/ITimbradoService/GetCfdiTestResponse")]
        ServiceReference1.ResponseTimbrado GetCfdiTest(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/GetCfdiTest", ReplyAction="http://tempuri.org/ITimbradoService/GetCfdiTestResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> GetCfdiTestAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Cancelar", ReplyAction="http://tempuri.org/ITimbradoService/CancelarResponse")]
        ServiceReference1.ResponseCancelacion Cancelar(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/Cancelar", ReplyAction="http://tempuri.org/ITimbradoService/CancelarResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseCancelacion> CancelarAsync(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/CancelarTest", ReplyAction="http://tempuri.org/ITimbradoService/CancelarTestResponse")]
        ServiceReference1.ResponseCancelacion CancelarTest(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/CancelarTest", ReplyAction="http://tempuri.org/ITimbradoService/CancelarTestResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseCancelacion> CancelarTestAsync(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerPeticionesPendientes", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerPeticionesPendientesResponse")]
        ServiceReference1.ResponsePeticionesPendientes ObtenerPeticionesPendientes(string RFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerPeticionesPendientes", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerPeticionesPendientesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponsePeticionesPendientes> ObtenerPeticionesPendientesAsync(string RFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionados", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionadosResponse")]
        ServiceReference1.ResponseConsultaCfdisRelacionados ObtenerCfdisRelacionados(string rfcReceptor, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionados", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionadosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaCfdisRelacionados> ObtenerCfdisRelacionadosAsync(string rfcReceptor, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionadosEmisor", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionadosEmisorResponse")]
        ServiceReference1.ResponseConsultaCfdisRelacionados ObtenerCfdisRelacionadosEmisor(string rfcEmisor, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionadosEmisor", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerCfdisRelacionadosEmisorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaCfdisRelacionados> ObtenerCfdisRelacionadosEmisorAsync(string rfcEmisor, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ConsultaEstatusSAT", ReplyAction="http://tempuri.org/ITimbradoService/ConsultaEstatusSATResponse")]
        ServiceReference1.ResponseConsultaEstatus ConsultaEstatusSAT(string rfcEmisor, string rfcReceptor, string total, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ConsultaEstatusSAT", ReplyAction="http://tempuri.org/ITimbradoService/ConsultaEstatusSATResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaEstatus> ConsultaEstatusSATAsync(string rfcEmisor, string rfcReceptor, string total, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AceptacionRechazo", ReplyAction="http://tempuri.org/ITimbradoService/AceptacionRechazoResponse")]
        ServiceReference1.ResponseAceptacionRechazo AceptacionRechazo(string rfcReceptor, string uuid, ServiceReference1.TipoAccionPeticionCancelacion respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AceptacionRechazo", ReplyAction="http://tempuri.org/ITimbradoService/AceptacionRechazoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseAceptacionRechazo> AceptacionRechazoAsync(string rfcReceptor, string uuid, ServiceReference1.TipoAccionPeticionCancelacion respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/GenerarPDF", ReplyAction="http://tempuri.org/ITimbradoService/GenerarPDFResponse")]
        ServiceReference1.Response GenerarPDF(string json, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/GenerarPDF", ReplyAction="http://tempuri.org/ITimbradoService/GenerarPDFResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> GenerarPDFAsync(string json, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSAP", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSAPResponse")]
        ServiceReference1.Response TimbrarSAP(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSAP", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSAPResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSAPAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSAPTest", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSAPTestResponse")]
        ServiceReference1.Response TimbrarSAPTest(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarSAPTest", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarSAPTestResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSAPTestAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/RecuperarPDFSAP", ReplyAction="http://tempuri.org/ITimbradoService/RecuperarPDFSAPResponse")]
        ServiceReference1.Response RecuperarPDFSAP(string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/RecuperarPDFSAP", ReplyAction="http://tempuri.org/ITimbradoService/RecuperarPDFSAPResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> RecuperarPDFSAPAsync(string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AltaEmpresaWithCertificado", ReplyAction="http://tempuri.org/ITimbradoService/AltaEmpresaWithCertificadoResponse")]
        string AltaEmpresaWithCertificado(string rfc, string razonSocial, string observaciones, byte[] cer, byte[] key, string contrasena, byte[] logo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AltaEmpresaWithCertificado", ReplyAction="http://tempuri.org/ITimbradoService/AltaEmpresaWithCertificadoResponse")]
        System.Threading.Tasks.Task<string> AltaEmpresaWithCertificadoAsync(string rfc, string razonSocial, string observaciones, byte[] cer, byte[] key, string contrasena, byte[] logo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AltaEmpresa", ReplyAction="http://tempuri.org/ITimbradoService/AltaEmpresaResponse")]
        string AltaEmpresa(string rfc, string razonSocial, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AltaEmpresa", ReplyAction="http://tempuri.org/ITimbradoService/AltaEmpresaResponse")]
        System.Threading.Tasks.Task<string> AltaEmpresaAsync(string rfc, string razonSocial, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AltaCertificado", ReplyAction="http://tempuri.org/ITimbradoService/AltaCertificadoResponse")]
        string AltaCertificado(string rfc, byte[] cer, byte[] key, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/AltaCertificado", ReplyAction="http://tempuri.org/ITimbradoService/AltaCertificadoResponse")]
        System.Threading.Tasks.Task<string> AltaCertificadoAsync(string rfc, byte[] cer, byte[] key, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ConsultaCertificado", ReplyAction="http://tempuri.org/ITimbradoService/ConsultaCertificadoResponse")]
        ServiceReference1.ResponseCertificado ConsultaCertificado(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ConsultaCertificado", ReplyAction="http://tempuri.org/ITimbradoService/ConsultaCertificadoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseCertificado> ConsultaCertificadoAsync(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ConsultaEmpresas", ReplyAction="http://tempuri.org/ITimbradoService/ConsultaEmpresasResponse")]
        ServiceReference1.ResponseConsultaEmpresas[] ConsultaEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ConsultaEmpresas", ReplyAction="http://tempuri.org/ITimbradoService/ConsultaEmpresasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaEmpresas[]> ConsultaEmpresasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerReporte", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerReporteResponse")]
        ServiceReference1.ResponseConsultaDetallada[] ObtenerReporte(bool productivo, System.DateTime fInicial, System.DateTime fFinal, string[] rfcs, string observaciones, bool timbresVigentes, bool timbresCancelados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerReporte", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerReporteResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaDetallada[]> ObtenerReporteAsync(bool productivo, System.DateTime fInicial, System.DateTime fFinal, string[] rfcs, string observaciones, bool timbresVigentes, bool timbresCancelados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarB64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarB64Response")]
        ServiceReference1.ResponseTimbradoBase64 TimbrarB64(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarB64", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarB64Response")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseTimbradoBase64> TimbrarB64Async(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarB64Test", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarB64TestResponse")]
        ServiceReference1.ResponseTimbradoBase64 TimbrarB64Test(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/TimbrarB64Test", ReplyAction="http://tempuri.org/ITimbradoService/TimbrarB64TestResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponseTimbradoBase64> TimbrarB64TestAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerComprobante", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerComprobanteResponse")]
        ServiceReference1.Response ObtenerComprobante(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/ObtenerComprobante", ReplyAction="http://tempuri.org/ITimbradoService/ObtenerComprobanteResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Response> ObtenerComprobanteAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/OPCumplimiento", ReplyAction="http://tempuri.org/ITimbradoService/OPCumplimientoResponse")]
        ServiceReference1.ResponsePDF OPCumplimiento(string pdf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimbradoService/OPCumplimiento", ReplyAction="http://tempuri.org/ITimbradoService/OPCumplimientoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResponsePDF> OPCumplimientoAsync(string pdf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ITimbradoServiceChannel : ServiceReference1.ITimbradoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TimbradoServiceClient : System.ServiceModel.ClientBase<ServiceReference1.ITimbradoService>, ServiceReference1.ITimbradoService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TimbradoServiceClient() : 
                base(TimbradoServiceClient.GetDefaultBinding(), TimbradoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITimbradoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TimbradoServiceClient.GetBindingForEndpoint(endpointConfiguration), TimbradoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TimbradoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TimbradoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.Response Timbrar(string json)
        {
            return base.Channel.Timbrar(json);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarAsync(string json)
        {
            return base.Channel.TimbrarAsync(json);
        }
        
        public ServiceReference1.Response TimbrarTest(string json)
        {
            return base.Channel.TimbrarTest(json);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarTestAsync(string json)
        {
            return base.Channel.TimbrarTestAsync(json);
        }
        
        public ServiceReference1.Response Timbrar40(string json)
        {
            return base.Channel.Timbrar40(json);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> Timbrar40Async(string json)
        {
            return base.Channel.Timbrar40Async(json);
        }
        
        public ServiceReference1.Response Timbrar40Test(string json)
        {
            return base.Channel.Timbrar40Test(json);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> Timbrar40TestAsync(string json)
        {
            return base.Channel.Timbrar40TestAsync(json);
        }
        
        public ServiceReference1.Response TimbrarSellarBase64(string xml)
        {
            return base.Channel.TimbrarSellarBase64(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSellarBase64Async(string xml)
        {
            return base.Channel.TimbrarSellarBase64Async(xml);
        }
        
        public ServiceReference1.Response TimbrarSellarBase64Test(string xml)
        {
            return base.Channel.TimbrarSellarBase64Test(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSellarBase64TestAsync(string xml)
        {
            return base.Channel.TimbrarSellarBase64TestAsync(xml);
        }
        
        public ServiceReference1.ResponseTimbrado TimbrarBase64(string xml)
        {
            return base.Channel.TimbrarBase64(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> TimbrarBase64Async(string xml)
        {
            return base.Channel.TimbrarBase64Async(xml);
        }
        
        public ServiceReference1.ResponseTimbrado TimbrarTestBase64(string xml)
        {
            return base.Channel.TimbrarTestBase64(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> TimbrarTestBase64Async(string xml)
        {
            return base.Channel.TimbrarTestBase64Async(xml);
        }
        
        public ServiceReference1.ResponseTimbrado GetCfdi(string xml)
        {
            return base.Channel.GetCfdi(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> GetCfdiAsync(string xml)
        {
            return base.Channel.GetCfdiAsync(xml);
        }
        
        public ServiceReference1.ResponseTimbrado GetCfdiTest(string xml)
        {
            return base.Channel.GetCfdiTest(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseTimbrado> GetCfdiTestAsync(string xml)
        {
            return base.Channel.GetCfdiTestAsync(xml);
        }
        
        public ServiceReference1.ResponseCancelacion Cancelar(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion)
        {
            return base.Channel.Cancelar(RfcEmisor, UUID, Motivo, FolioSustitucion);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseCancelacion> CancelarAsync(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion)
        {
            return base.Channel.CancelarAsync(RfcEmisor, UUID, Motivo, FolioSustitucion);
        }
        
        public ServiceReference1.ResponseCancelacion CancelarTest(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion)
        {
            return base.Channel.CancelarTest(RfcEmisor, UUID, Motivo, FolioSustitucion);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseCancelacion> CancelarTestAsync(string RfcEmisor, string UUID, string Motivo, string FolioSustitucion)
        {
            return base.Channel.CancelarTestAsync(RfcEmisor, UUID, Motivo, FolioSustitucion);
        }
        
        public ServiceReference1.ResponsePeticionesPendientes ObtenerPeticionesPendientes(string RFC)
        {
            return base.Channel.ObtenerPeticionesPendientes(RFC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponsePeticionesPendientes> ObtenerPeticionesPendientesAsync(string RFC)
        {
            return base.Channel.ObtenerPeticionesPendientesAsync(RFC);
        }
        
        public ServiceReference1.ResponseConsultaCfdisRelacionados ObtenerCfdisRelacionados(string rfcReceptor, string uuid)
        {
            return base.Channel.ObtenerCfdisRelacionados(rfcReceptor, uuid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaCfdisRelacionados> ObtenerCfdisRelacionadosAsync(string rfcReceptor, string uuid)
        {
            return base.Channel.ObtenerCfdisRelacionadosAsync(rfcReceptor, uuid);
        }
        
        public ServiceReference1.ResponseConsultaCfdisRelacionados ObtenerCfdisRelacionadosEmisor(string rfcEmisor, string uuid)
        {
            return base.Channel.ObtenerCfdisRelacionadosEmisor(rfcEmisor, uuid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaCfdisRelacionados> ObtenerCfdisRelacionadosEmisorAsync(string rfcEmisor, string uuid)
        {
            return base.Channel.ObtenerCfdisRelacionadosEmisorAsync(rfcEmisor, uuid);
        }
        
        public ServiceReference1.ResponseConsultaEstatus ConsultaEstatusSAT(string rfcEmisor, string rfcReceptor, string total, string uuid)
        {
            return base.Channel.ConsultaEstatusSAT(rfcEmisor, rfcReceptor, total, uuid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaEstatus> ConsultaEstatusSATAsync(string rfcEmisor, string rfcReceptor, string total, string uuid)
        {
            return base.Channel.ConsultaEstatusSATAsync(rfcEmisor, rfcReceptor, total, uuid);
        }
        
        public ServiceReference1.ResponseAceptacionRechazo AceptacionRechazo(string rfcReceptor, string uuid, ServiceReference1.TipoAccionPeticionCancelacion respuesta)
        {
            return base.Channel.AceptacionRechazo(rfcReceptor, uuid, respuesta);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseAceptacionRechazo> AceptacionRechazoAsync(string rfcReceptor, string uuid, ServiceReference1.TipoAccionPeticionCancelacion respuesta)
        {
            return base.Channel.AceptacionRechazoAsync(rfcReceptor, uuid, respuesta);
        }
        
        public ServiceReference1.Response GenerarPDF(string json, string xml)
        {
            return base.Channel.GenerarPDF(json, xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> GenerarPDFAsync(string json, string xml)
        {
            return base.Channel.GenerarPDFAsync(json, xml);
        }
        
        public ServiceReference1.Response TimbrarSAP(string xml)
        {
            return base.Channel.TimbrarSAP(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSAPAsync(string xml)
        {
            return base.Channel.TimbrarSAPAsync(xml);
        }
        
        public ServiceReference1.Response TimbrarSAPTest(string xml)
        {
            return base.Channel.TimbrarSAPTest(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> TimbrarSAPTestAsync(string xml)
        {
            return base.Channel.TimbrarSAPTestAsync(xml);
        }
        
        public ServiceReference1.Response RecuperarPDFSAP(string uuid)
        {
            return base.Channel.RecuperarPDFSAP(uuid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> RecuperarPDFSAPAsync(string uuid)
        {
            return base.Channel.RecuperarPDFSAPAsync(uuid);
        }
        
        public string AltaEmpresaWithCertificado(string rfc, string razonSocial, string observaciones, byte[] cer, byte[] key, string contrasena, byte[] logo)
        {
            return base.Channel.AltaEmpresaWithCertificado(rfc, razonSocial, observaciones, cer, key, contrasena, logo);
        }
        
        public System.Threading.Tasks.Task<string> AltaEmpresaWithCertificadoAsync(string rfc, string razonSocial, string observaciones, byte[] cer, byte[] key, string contrasena, byte[] logo)
        {
            return base.Channel.AltaEmpresaWithCertificadoAsync(rfc, razonSocial, observaciones, cer, key, contrasena, logo);
        }
        
        public string AltaEmpresa(string rfc, string razonSocial, string observaciones)
        {
            return base.Channel.AltaEmpresa(rfc, razonSocial, observaciones);
        }
        
        public System.Threading.Tasks.Task<string> AltaEmpresaAsync(string rfc, string razonSocial, string observaciones)
        {
            return base.Channel.AltaEmpresaAsync(rfc, razonSocial, observaciones);
        }
        
        public string AltaCertificado(string rfc, byte[] cer, byte[] key, string contrasena)
        {
            return base.Channel.AltaCertificado(rfc, cer, key, contrasena);
        }
        
        public System.Threading.Tasks.Task<string> AltaCertificadoAsync(string rfc, byte[] cer, byte[] key, string contrasena)
        {
            return base.Channel.AltaCertificadoAsync(rfc, cer, key, contrasena);
        }
        
        public ServiceReference1.ResponseCertificado ConsultaCertificado(string rfc)
        {
            return base.Channel.ConsultaCertificado(rfc);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseCertificado> ConsultaCertificadoAsync(string rfc)
        {
            return base.Channel.ConsultaCertificadoAsync(rfc);
        }
        
        public ServiceReference1.ResponseConsultaEmpresas[] ConsultaEmpresas()
        {
            return base.Channel.ConsultaEmpresas();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaEmpresas[]> ConsultaEmpresasAsync()
        {
            return base.Channel.ConsultaEmpresasAsync();
        }
        
        public ServiceReference1.ResponseConsultaDetallada[] ObtenerReporte(bool productivo, System.DateTime fInicial, System.DateTime fFinal, string[] rfcs, string observaciones, bool timbresVigentes, bool timbresCancelados)
        {
            return base.Channel.ObtenerReporte(productivo, fInicial, fFinal, rfcs, observaciones, timbresVigentes, timbresCancelados);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseConsultaDetallada[]> ObtenerReporteAsync(bool productivo, System.DateTime fInicial, System.DateTime fFinal, string[] rfcs, string observaciones, bool timbresVigentes, bool timbresCancelados)
        {
            return base.Channel.ObtenerReporteAsync(productivo, fInicial, fFinal, rfcs, observaciones, timbresVigentes, timbresCancelados);
        }
        
        public ServiceReference1.ResponseTimbradoBase64 TimbrarB64(string xml)
        {
            return base.Channel.TimbrarB64(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseTimbradoBase64> TimbrarB64Async(string xml)
        {
            return base.Channel.TimbrarB64Async(xml);
        }
        
        public ServiceReference1.ResponseTimbradoBase64 TimbrarB64Test(string xml)
        {
            return base.Channel.TimbrarB64Test(xml);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseTimbradoBase64> TimbrarB64TestAsync(string xml)
        {
            return base.Channel.TimbrarB64TestAsync(xml);
        }
        
        public ServiceReference1.Response ObtenerComprobante(string UUID)
        {
            return base.Channel.ObtenerComprobante(UUID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Response> ObtenerComprobanteAsync(string UUID)
        {
            return base.Channel.ObtenerComprobanteAsync(UUID);
        }
        
        public ServiceReference1.ResponsePDF OPCumplimiento(string pdf)
        {
            return base.Channel.OPCumplimiento(pdf);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponsePDF> OPCumplimientoAsync(string pdf)
        {
            return base.Channel.OPCumplimientoAsync(pdf);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITimbradoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITimbradoService))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.digitalinvoice.com.mx/WSDI_SEP/TimbradoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TimbradoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITimbradoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TimbradoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITimbradoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITimbradoService,
        }
    }
}
