-- ============================================================================
-- Alinear los ids de tpdoc de producción (srs_prod) con los de desarrollo (srs)
--
-- PROBLEMA
-- Los mismos 9 tipos de documento se dieron de alta en producción en orden
-- inverso, así que el bloque 82–92 quedó reflejado alrededor del 87:
--
--        id | desarrollo | producción
--        82 | FSGTO      | GLFAC
--        83 | CARLAY     | MIKEP
--        84 | RMP        | MODPED
--        85 | DISM       | (vacío)
--        86 | EDC        | TYBPED
--        87 | TYBCOT     | TYBCOT      ← coincide
--        88 | TYBPED     | EDC
--        89 | MODPED     | DISM
--        90 | MIKEP      | RMP
--        91 | GLFAC      | CARLAY
--        92 | (vacío)    | FSGTO
--
-- Como el código pasa el id fijo a sp_generar_documento_con_partidas y esa
-- función deriva `nat` del id, en producción un GLFAC nacería como CARLAY.
--
-- POR QUÉ SE PUEDE RENUMERAR SIN RIESGO
-- Ninguno de los 9 ids tiene, en producción, un solo documento en encabezadomov,
-- folio en foldoc, configuración en poliza_documento, flujo en tpdoc_flujo ni
-- relación en tpdoc_doc_kepler_rel. Son filas de catálogo sin uso: es el momento
-- más barato en que se podrá corregir.
--
-- CÓMO CORRERLO
-- Va todo en una transacción y TERMINA EN ROLLBACK a propósito. Revisa el
-- resultado de la verificación final; si dice 0 diferencias, cambia el ROLLBACK
-- por COMMIT y vuelve a correrlo.
-- ============================================================================

BEGIN;

-- ── 0. Red de seguridad: si algún id ya se usara, aborta ────────────────────
DO $$
DECLARE
    v_usos integer;
BEGIN
    SELECT COUNT(*) INTO v_usos FROM (
        SELECT 1 FROM srs_prod.encabezadomov      WHERE nro_tp_doc     IN (82,83,84,86,88,89,90,91,92)
        UNION ALL
        SELECT 1 FROM srs_prod.foldoc             WHERE tpdocid        IN (82,83,84,86,88,89,90,91,92)
        UNION ALL
        SELECT 1 FROM srs_prod.poliza_documento   WHERE idtpdoc        IN (82,83,84,86,88,89,90,91,92)
        UNION ALL
        SELECT 1 FROM srs_prod.tpdoc_doc_kepler_rel WHERE idtpdoc      IN (82,83,84,86,88,89,90,91,92)
        UNION ALL
        SELECT 1 FROM srs_prod.tpdoc_flujo        WHERE idtpdoc_origen IN (82,83,84,86,88,89,90,91,92)
                                                     OR idtpdoc_destino IN (82,83,84,86,88,89,90,91,92)
    ) x;

    IF v_usos > 0 THEN
        RAISE EXCEPTION
            'ABORTADO: % filas ya usan alguno de los ids a renumerar. Renumerar ahora rompería datos existentes.', v_usos;
    END IF;
END $$;

-- ── 1. Permitir escribir la columna de identidad ────────────────────────────
-- GENERATED ALWAYS bloquea el UPDATE; se baja a BY DEFAULT y se restaura al final.
ALTER TABLE srs_prod.tpdoc ALTER COLUMN idtpdoc SET GENERATED BY DEFAULT;

-- ── 2. Estacionar fuera de rango ────────────────────────────────────────────
-- Es una permutación cerrada (82↔91, 83↔90, …): mover directo chocaría con la
-- llave primaria a medio camino, así que primero se apartan todos.
UPDATE srs_prod.tpdoc
SET idtpdoc = idtpdoc + 1000
WHERE idtpdoc IN (82,83,84,86,88,89,90,91,92);

-- ── 3. Aterrizar en el id que usa desarrollo ────────────────────────────────
UPDATE srs_prod.tpdoc
SET idtpdoc = m.destino
FROM (VALUES
    (1082, 91),   -- GLFAC
    (1083, 90),   -- MIKEP
    (1084, 89),   -- MODPED
    (1086, 88),   -- TYBPED
    (1088, 86),   -- EDC
    (1089, 85),   -- DISM
    (1090, 84),   -- RMP
    (1091, 83),   -- CARLAY
    (1092, 82)    -- FSGTO
) AS m(origen, destino)
WHERE srs_prod.tpdoc.idtpdoc = m.origen;

-- ── 4. Restaurar la identidad y reposicionar la secuencia ───────────────────
-- SET GENERATED ALWAYS, no ADD: la columna sigue siendo de identidad, sólo
-- cambia el modo. Con ADD, PostgreSQL responde "ya es una columna de identidad".
ALTER TABLE srs_prod.tpdoc ALTER COLUMN idtpdoc SET GENERATED ALWAYS;

SELECT setval(pg_get_serial_sequence('srs_prod.tpdoc','idtpdoc'),
              (SELECT MAX(idtpdoc) FROM srs_prod.tpdoc));

-- ── 5. Verificación ─────────────────────────────────────────────────────────
-- Debe devolver 0. Si no, NO hagas COMMIT.
SELECT COUNT(*) AS diferencias_restantes
FROM srs.tpdoc d
FULL OUTER JOIN srs_prod.tpdoc p ON p.idtpdoc = d.idtpdoc
WHERE d.abreviaturatpdoc IS DISTINCT FROM p.abreviaturatpdoc
  AND COALESCE(d.abreviaturatpdoc, p.abreviaturatpdoc) <> 'PENDIENTE'
  AND COALESCE(d.idtpdoc, p.idtpdoc) <> 93;   -- FACLIB, que aún no existe en producción

-- Detalle de lo que quede distinto, para revisarlo a ojo.
SELECT COALESCE(d.idtpdoc, p.idtpdoc) AS id,
       d.abreviaturatpdoc AS dev, p.abreviaturatpdoc AS prod
FROM srs.tpdoc d
FULL OUTER JOIN srs_prod.tpdoc p ON p.idtpdoc = d.idtpdoc
WHERE d.abreviaturatpdoc IS DISTINCT FROM p.abreviaturatpdoc
ORDER BY 1;

-- Cambia esto por COMMIT cuando la verificación salga en 0.
ROLLBACK;
