<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<Features>
		experimental-data-section-string-literals
	</Features>
  </PropertyGroup>
  <ItemGroup>
    <None Include="wwwroot\scripts\Almacen\agencys.js" />
    <None Include="wwwroot\scripts\Almacen\almacenes.js" />
    <None Include="wwwroot\scripts\Almacen\grupos.js" />
    <None Include="wwwroot\scripts\Almacen\lineas.js" />
    <None Include="wwwroot\scripts\Almacen\lines.js" />
    <None Include="wwwroot\scripts\Almacen\Productos\productos.js" />
    <None Include="wwwroot\scripts\Almacen\solicitud-material.js" />
    <None Include="wwwroot\scripts\Almacen\tipos.js" />
    <None Include="wwwroot\scripts\Almacen\types.js" />
    <None Include="wwwroot\scripts\Almacen\unidades.js" />
    <None Include="wwwroot\scripts\Almacen\units.js" />
    <None Include="wwwroot\scripts\Almacen\warehouses.js" />
    <None Include="wwwroot\scripts\Carteras\ReporteCarteraGraficas.js" />
    <None Include="wwwroot\scripts\Carteras\ReporteCarteraPdf.js" />
    <None Include="wwwroot\scripts\Confetti.js" />
    <None Include="wwwroot\scripts\Contabilidad\concepts.js" />
    <None Include="wwwroot\scripts\Contabilidad\departments.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\aplicacion_notas_credito.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\complemento_pago.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\Facturacion_Especial\partial-vin-cotizacion.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\Facturacion_Especial\partial-vin-factura.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\incoterms.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\typeclients.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\vendedores.js" />
    <None Include="wwwroot\scripts\Credito_Cobranza\zones.js" />
    <None Include="wwwroot\scripts\CuentasXPagar\agentescompra.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.bootstrap.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.bootstrap.min.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.bootstrap4.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.bootstrap4.min.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.foundation.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.foundation.min.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.jqueryui.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.jqueryui.min.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.semanticui.js" />
    <None Include="wwwroot\scripts\DataTables\autoFill.semanticui.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.bootstrap.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.bootstrap.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.bootstrap4.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.bootstrap4.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.colVis.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.colVis.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.flash.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.flash.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.foundation.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.foundation.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.html5.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.html5.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.jqueryui.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.jqueryui.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.print.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.print.min.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.semanticui.js" />
    <None Include="wwwroot\scripts\DataTables\buttons.semanticui.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.autoFill.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.autoFill.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.bootstrap.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.bootstrap.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.bootstrap4.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.bootstrap4.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.buttons.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.buttons.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.colReorder.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.colReorder.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.fixedColumns.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.fixedColumns.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.fixedHeader.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.fixedHeader.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.foundation.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.foundation.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.jqueryui.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.jqueryui.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.keyTable.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.keyTable.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.material.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.material.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.responsive.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.responsive.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.rowGroup.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.rowGroup.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.rowReorder.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.rowReorder.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.scroller.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.scroller.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.select.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.select.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.semanticui.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.semanticui.min.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.uikit.js" />
    <None Include="wwwroot\scripts\DataTables\dataTables.uikit.min.js" />
    <None Include="wwwroot\scripts\DataTables\jquery.dataTables.js" />
    <None Include="wwwroot\scripts\DataTables\jquery.dataTables.min.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.bootstrap.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.bootstrap.min.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.bootstrap4.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.bootstrap4.min.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.foundation.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.foundation.min.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.jqueryui.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.jqueryui.min.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.semanticui.js" />
    <None Include="wwwroot\scripts\DataTables\responsive.semanticui.min.js" />
    <None Include="wwwroot\scripts\Facturas\manejo-respuestas.js" />
    <None Include="wwwroot\scripts\Facturas\nc-business-rules.js" />
    <None Include="wwwroot\scripts\Facturas\nota-credito.js" />
    <None Include="wwwroot\scripts\Facturas\reporte-danado.js" />
    <None Include="wwwroot\scripts\Facturas\solicitud-nc.js" />
    <None Include="wwwroot\scripts\flujo-documento.js" />
    <None Include="wwwroot\scripts\formularios.js" />
    <None Include="wwwroot\scripts\Gastos\gastos-engine.js" />
    <None Include="wwwroot\scripts\Gastos\gastos-schema.js" />
    <None Include="wwwroot\scripts\General\general.js" />
    <None Include="wwwroot\scripts\GenerarPDF.js" />
    <None Include="wwwroot\scripts\InfoModals.js" />
    <None Include="wwwroot\scripts\Inventario\busqueda.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\almacen-virtual.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\app-ocupacion.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\app-plano.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\data.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\details.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\inventario-virtual.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\map-view.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\rack-inspector.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\rack-view.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\search-route.js" />
    <None Include="wwwroot\scripts\Inventario\Consulta\treemap-view.js" />
    <None Include="wwwroot\scripts\Inventario\konva-diseño.js" />
    <None Include="wwwroot\scripts\Inventario\navegacion-inventario.js" />
    <None Include="wwwroot\scripts\Inventario\renderizar-cards-jerarquía.js" />
    <None Include="wwwroot\scripts\Inventario\reporte.js" />
    <None Include="wwwroot\scripts\Kits\crear-kit.js" />
    <None Include="wwwroot\scripts\Notify.js" />
    <None Include="wwwroot\scripts\Operaciones\Cotizacion\buscadores.js" />
    <None Include="wwwroot\scripts\Operaciones\Pedido\buscadores.js" />
    <None Include="wwwroot\scripts\Operaciones\Requisicion\buscadores.js" />
    <None Include="wwwroot\scripts\Refacturacion\catalogos.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\adenda - Copia.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\anticipo.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\complemento-pago.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\conceptos.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\datos-fiscales.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\devolucion.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\factura-pagada.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\forma-pago.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\impuestos.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\metodo-pago.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\moneda.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\parcial.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\adenda.js" />
    <None Include="wwwroot\scripts\Refacturacion\handlers\parcialidades.js" />
    <None Include="wwwroot\scripts\Refacturacion\state.js" />
    <None Include="wwwroot\scripts\Refacturacion\step4.js" />
    <None Include="wwwroot\scripts\Refacturacion\step5.js" />
    <None Include="wwwroot\scripts\Refacturacion\utils.js" />
    <None Include="wwwroot\scripts\Requisicion\requisicion-form.js" />
    <None Include="wwwroot\scripts\Requisicion\requisicion-index.js" />
    <None Include="wwwroot\scripts\sidebar.js" />
    <None Include="wwwroot\scripts\site1.js" />
    <None Include="wwwroot\scripts\Soporte\ticket-administracion-categoria.js" />
    <None Include="wwwroot\scripts\Soporte\ticket-administracion-equipo.js" />
    <None Include="wwwroot\scripts\Soporte\ticket-administracion-informe.js" />
    <None Include="wwwroot\scripts\Soporte\ticket-administracion-ticket.js" />
    <None Include="wwwroot\scripts\Soporte\ticket-buscarticket.js" />
    <None Include="wwwroot\scripts\Soporte\ticket-formulario.js" />
    <None Include="wwwroot\scripts\Soporte\ticket-info-usuario.js" />
    <None Include="wwwroot\scripts\Switch.js" />
    <None Include="wwwroot\scripts\TableBuilder.js" />
    <None Include="wwwroot\scripts\Tesoreria\banks.js" />
    <None Include="wwwroot\scripts\Tesoreria\banksSAT.js" />
    <None Include="wwwroot\scripts\Ventas\Industriales\facturacion-remisiones-parciales.js" />
    <None Include="wwwroot\scripts\Ventas\Industriales\partial-vi-cotizacion.js" />
    <None Include="wwwroot\scripts\Ventas\Industriales\partial-vi-factura-anticipo.js" />
    <None Include="wwwroot\scripts\Ventas\Industriales\partial-vi-factura.js" />
    <None Include="wwwroot\scripts\Ventas\Industriales\partial-vi-pedido.js" />
    <None Include="wwwroot\scripts\Ventas\Industriales\partial-vi-remision.js" />
    <None Include="wwwroot\scripts\Ventas\Internacionales\FacturasRemisionParcialesManager_VIN.js" />
    <None Include="wwwroot\scripts\Ventas\Internacionales\partial-vin-cotizacion-asistida.js" />
    <None Include="wwwroot\scripts\Ventas\Internacionales\partial-vin-cotizacion.js" />
    <None Include="wwwroot\scripts\Ventas\Internacionales\partial-vin-factura.js" />
    <None Include="wwwroot\scripts\Ventas\Internacionales\partial-vin-pedido.js" />
    <None Include="wwwroot\scripts\Ventas\Internacionales\partial-vin-remision.js" />
    <None Include="wwwroot\scripts\Ventas\Nacionales\partial-vn-cotizacion.js" />
    <None Include="wwwroot\scripts\Ventas\Nacionales\partial-vn-factura.js" />
    <None Include="wwwroot\scripts\Ventas\Nacionales\partial-vn-pedido.js" />
    <None Include="wwwroot\scripts\Ventas\Nacionales\partial-vn-remision.js" />
    <None Include="wwwroot\scripts\Ventas\partial-vn-cotizacion.js" />
    <None Include="wwwroot\scripts\Ventas\partial-vn-factura - Copia.js" />
    <None Include="wwwroot\scripts\Ventas\partial-vn-factura.js" />
    <None Include="wwwroot\scripts\Ventas\partial-vn-pedido.js" />
    <None Include="wwwroot\scripts\Ventas\partial-vn-remision.js" />
    <None Include="wwwroot\scripts\Ventas\Sucursales\partial-vs-cotizacion.js" />
    <None Include="wwwroot\scripts\Ventas\Sucursales\partial-vs-factura.js" />
    <None Include="wwwroot\scripts\Ventas\Sucursales\partial-vs-pedido.js" />
    <None Include="wwwroot\scripts\Ventas\Sucursales\partial-vs-remision.js" />
    <None Include="wwwroot\scripts\Ventas\Tubos\adminCortes.js" />
    <None Include="wwwroot\scripts\Ventas\Tubos\corteOperacion.js" />
    <None Include="wwwroot\scripts\Ventas\Tubos\partial-vt-pedido.js" />
    <None Include="wwwroot\scripts\Ventas\Tubos\partial-vt-cotizacion.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="MySql.Data" Version="9.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="PusherServer" Version="5.0.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="Rotativa.AspNetCore" Version="1.4.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="8.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="8.*" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.*" />
  </ItemGroup>
	<ItemGroup>
		<None Include="Rotativa\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="wwwroot\echarts\**" />
	  <Content Remove="wwwroot\echarts\**" />
	  <EmbeddedResource Remove="wwwroot\echarts\**" />
	  <None Remove="wwwroot\echarts\**" />
	</ItemGroup>
	<ItemGroup>
	  <Content Remove="wwwroot\scripts\Refacturacion\handlers\adenda - Copia.js" />
	  <Content Remove="wwwroot\scripts\Refacturacion\handlers\adenda.js" />
	  <Content Remove="wwwroot\scripts\Ventas\Tubos\adminCortes.js" />
	  <Content Remove="wwwroot\scripts\Ventas\Tubos\corteOperacion.js" />
	  <Content Remove="wwwroot\scripts\Ventas\Tubos\partial-vt-cotizacion.js" />
	  <Content Remove="wwwroot\scripts\Ventas\Tubos\partial-vt-pedido.js" />
	</ItemGroup>
	<!-- Artefactos generados en runtime (PDF/XML/acuses de facturación): se excluyen del
	     watch de dotnet watch / Hot Reload para que escribirlos NO recargue el navegador. -->
	<ItemGroup>
	  <Content Update="wwwroot\Facturacion\**\*" Watch="false" />
	</ItemGroup>
</Project>